/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThreatHuntingRouteImport } from './routes/threat-hunting'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as MitreRouteImport } from './routes/mitre'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AiAnalystRouteImport } from './routes/ai-analyst'
import { Route as IndexRouteImport } from './routes/index'

const ThreatHuntingRoute = ThreatHuntingRouteImport.update({
  id: '/threat-hunting',
  path: '/threat-hunting',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MitreRoute = MitreRouteImport.update({
  id: '/mitre',
  path: '/mitre',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAnalystRoute = AiAnalystRouteImport.update({
  id: '/ai-analyst',
  path: '/ai-analyst',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-analyst': typeof AiAnalystRoute
  '/alerts': typeof AlertsRoute
  '/incidents': typeof IncidentsRoute
  '/mitre': typeof MitreRoute
  '/reports': typeof ReportsRoute
  '/threat-hunting': typeof ThreatHuntingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-analyst': typeof AiAnalystRoute
  '/alerts': typeof AlertsRoute
  '/incidents': typeof IncidentsRoute
  '/mitre': typeof MitreRoute
  '/reports': typeof ReportsRoute
  '/threat-hunting': typeof ThreatHuntingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-analyst': typeof AiAnalystRoute
  '/alerts': typeof AlertsRoute
  '/incidents': typeof IncidentsRoute
  '/mitre': typeof MitreRoute
  '/reports': typeof ReportsRoute
  '/threat-hunting': typeof ThreatHuntingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-analyst'
    | '/alerts'
    | '/incidents'
    | '/mitre'
    | '/reports'
    | '/threat-hunting'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-analyst'
    | '/alerts'
    | '/incidents'
    | '/mitre'
    | '/reports'
    | '/threat-hunting'
  id:
    | '__root__'
    | '/'
    | '/ai-analyst'
    | '/alerts'
    | '/incidents'
    | '/mitre'
    | '/reports'
    | '/threat-hunting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAnalystRoute: typeof AiAnalystRoute
  AlertsRoute: typeof AlertsRoute
  IncidentsRoute: typeof IncidentsRoute
  MitreRoute: typeof MitreRoute
  ReportsRoute: typeof ReportsRoute
  ThreatHuntingRoute: typeof ThreatHuntingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/threat-hunting': {
      id: '/threat-hunting'
      path: '/threat-hunting'
      fullPath: '/threat-hunting'
      preLoaderRoute: typeof ThreatHuntingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitre': {
      id: '/mitre'
      path: '/mitre'
      fullPath: '/mitre'
      preLoaderRoute: typeof MitreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-analyst': {
      id: '/ai-analyst'
      path: '/ai-analyst'
      fullPath: '/ai-analyst'
      preLoaderRoute: typeof AiAnalystRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAnalystRoute: AiAnalystRoute,
  AlertsRoute: AlertsRoute,
  IncidentsRoute: IncidentsRoute,
  MitreRoute: MitreRoute,
  ReportsRoute: ReportsRoute,
  ThreatHuntingRoute: ThreatHuntingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
